---
wp_mysql_user: local
wp_mysql_db: wordpress
wp_mysql_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62366435613330613763303964303834633262373031313039373835393036366134643434343531
      6335666636376235336139323939336332303366646538390a613662303463353331626663623864
      30303435626137393633316166313532333830643866336464383734653638616663656565613435
      3264353761336233650a656431363636396430343034336666386464316666643331336463353631
      3330
