---
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.56.0/24
  - 10.0.2.0/24
  - localhost
  - 172.17.0.0/16
records:
  - type: NS
    entries:
      - name: zekena.ttu.
        address: infra01.zekena.ttu.
      - name: zekena.ttu.
        address: infra02.zekena.ttu.
  - type: A
    entries:
      - name: infra01.zekena.ttu.
        address: 192.168.56.101
      - name: infra02.zekena.ttu.
        address: 192.168.56.102
      - name: infra.zekena.ttu.
        addresses:
          - 192.168.56.101
          - 192.168.56.102
  - type: CNAME
    entries:
      - name: ns
        address: infra
      - name: ns1
        address: infra01
      - name: ns2
        address: infra02
      - name: www
        address: infra01
      - name: grafana
        address: infra01
      - name: prometheus
        address: infra02
      - name: influxdb
        address: infra02
      - name: db
        address: infra02
