- name: dns package
  apt:
    name: bind9
    state: present
- name: config bind
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
    - restart bind
    - check conf

- name: config bind.local
  template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - check conf
    - restart bind

- name: check zone hash
  copy:
    content: "{{ records|hash }}"
    dest: /etc/bind/db.zekena.hash
  when: dns_role == "master"
  notify:
    - get timestamp
    - upload bind zone
    - restart bind
    - bind reload db
  tags:
    - j

- name: config db ptr
  template:
    src: templates/db.zekena.ptr.j2
    dest: /etc/bind/db.zekena.ptr
  when: dns_role == "master"
  notify:
    - restart bind
    - bind reload db
- name: check that file exists
  stat:
    path: /opt/bind_exporte
  register: stat_result1

- name: download go
  get_url:
    url: https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz
    dest: /opt/go1.13.3.linux-amd64.tar.gz
  when: stat_result1.stat.exists == False
- name: folder
  file:
    path: /opt/go
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/go1.13.3.linux-amd64.tar.gz
    dest: /opt/go
    remote_src: yes

- name: Create a symbolic link
  file:
    src: /opt/go/go/bin/go
    dest: /usr/local/bin/go
    state: link

- name: Check that the file exists
  stat:
    path: /root/go/src/github.com/digitalocean/bind_exporter/bind_exporter.go
  register: stat_result

- name: go get
  shell: "go get github.com/digitalocean/bind_exporter"
  when: stat_result.stat.exists == False

- name: copy binary
  copy:
    src: /root/go/bin/bind_exporter
    dest: /usr/local/bin/bind_exporter
    mode: u=rwx,g=rx,o=rx
    remote_src: yes

- name: make a service
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service

- name: start bind_exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - bind9
    - bind_exporter

- name: resolv.conf fix
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
